#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LocalNews.Droid.Resource", IsApplication=true)]

namespace LocalNews.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int ic_action_delete = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ic_action_favorite = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ic_action_favorite_border = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_action_open_in_browser = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ic_action_search = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ic_airplay = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int ic_favorite = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int ic_flag = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int ic_home = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int ic_language = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int ic_launcher = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int ic_receipt = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int ic_shortcut_favorite = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int ic_shortcut_favorite_border = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int ic_update = 2130771982;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int sliding_tabs = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int toolbar = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Tabbar = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int AppCompatDialogStyle = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MainTheme = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MainTheme_Base = 2130968578;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
